### PR TITLE
Restrict egress

### PR DESCRIPTION
**Pull request by adborden**
Locks down the egress permissions a little so that only 80/443 are allowed, plus a few exceptions based on services required (db, solr, ssh, etc)

### CODE REVIEW

**Comment by pburkholder** [comment]
Won't there also need to be egress to DNS servers? Based on what I read at https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html I think that would be egress to the same VPC, e.g.

```
egress {
 from_port   = 22
 to_port     = 22
 protocol    = "udp"
 cidr_blocks = ["10.0.0.0/8"]
 }
```

Also, is there any shipping of system logs?

P

**Comment by adborden** [comment]
Hmm, that's a good question. In my testing, I was still able to make DNS requests with this setup. I think AWS does something special with a few protocols, like DNS. For example, DHCP is 68/udp, and that's not whitelisted.

I noticed this note in the [DHCP docs](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html#AmazonDNS):

> You cannot filter traffic to or from a DNS server using network ACLs or security groups.

I will double check these are valid one more time.

**Comment by adborden** [comment]
In the sandbox (where these templates are applied) there is no log shipping configured.

**Comment by adborden** [comment]
I just validated that with this configuration, DNS requests are still allowed :man_shrugging:

**Review by pburkholder — APPROVED** [review]

**Comment by adborden** [comment]
Rebased to resolve merge conflict.

**Pull request merged**
